### ISSUE TITLE
Using the minishift-addon installer with minikube should fail

### ISSUE THREAD

**Issue by l0rd** [che-incubator/chectl#101]
It should fail before the preflight check and provide a meaningful error. Instead it currently fails trying to install the addon:

```
chectl server:start -a minishift-addon
  √ ✈️  Minikube preflight checklist
    √ Verify if kubectl is installed
    √ Verify if minikube is installed
    √ Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    √ Verify userland-proxy is disabled...done.
    √ Verify if minikube ingress addon is enabled
    ↓ Enable minikube ingress addon [skipped]
      → Ingress addon is already enabled.
    √ Retrieving minikube IP and domain for ingress URLs...192.168.1.27.nip.io.
  √ 🏃‍  Running the Che minishift-addon
    √ Apply Che addon...done.
  > ✅  Post installation checklist
    > Che pod bootstrap
      × scheduling
        → ERR_TIMEOUT
        downloading images
        starting
      Retrieving Che Server URL
      Che status check
Error: ERR_TIMEOUT
    at KubeHelper.<anonymous> (C:/snapshot/chectl/lib/api/kube.js:0:0)
    at Generator.next (<anonymous>)
    at fulfilled (C:/snapshot/chectl/node_modules/tslib/tslib.js:104:62)
```

**Comment by amisevsk** [comment]
Something brought up on the eclipse mattermost that should probably be grouped in here, but one user did not get a meaningful error message when the Che addon was not installed (using minishift).
