### ISSUE TITLE
Error "Unexpected Phase" when starting che with Chectl

### ISSUE THREAD

**Issue by slemeur** [che-incubator/chectl#103]
When starting Che from chectl, this is the error I'm getting:
```
❯ ✅  Post installation checklist
    ❯ Che pod bootstrap
      ✖ scheduling
        → ERR_UNEXPECTED_PHASE: Running (Pending expected)
        downloading images
        starting
      Retrieving Che Server URL
      Che status check
Error: ERR_UNEXPECTED_PHASE: Running (Pending expected) 
    at KubeHelper.<anonymous> (/snapshot/chectl/lib/api/kube.js:0:0)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/chectl/node_modules/tslib/tslib.js:104:62)
```

**Comment by slemeur** [comment]
Get over the error by doing a `chectl server:delete` and then `chectl server:start`

**Comment by l0rd** [comment]
Duplicate of #48
