### ISSUE TITLE
chectl server:start fails with helm v2.14

### ISSUE THREAD

**Issue by vinokurig** [che-incubator/chectl#108]
Can not star che on minikube.
Executing `chectl servert:start` fails with an error: 
```chectl server:start
  ✔ ✈️  Minikube preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if minikube is installed
    ✔ Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    ✔ Verify userland-proxy is disabled...done.
    ✔ Verify if minikube ingress addon is enabled
    ↓ Enable minikube ingress addon [skipped]
      → Ingress addon is already enabled.
    ✔ Retrieving minikube IP and domain for ingress URLs...192.168.39.153.nip.io.
  ❯ 🏃‍  Running Helm to install Che
    ✔ Verify if helm is installed
    ✔ Create Tiller Role Binding...it already exist.
    ✔ Create Tiller Service Account...it already exist.
    ✔ Create Tiller RBAC
    ✔ Create Tiller Service...it already exist.
    ✔ Preparing Che Helm Chart...done.
    ✔ Updating Helm Chart dependencies...done.
    ✖ Deploying Che Helm Chart
      → Release "che" does not exist. Installing it now.
Error: Command failed: /bin/sh -c helm upgrade --install che --force --namespace che --set global.ingressDomain=192.168.39.153.nip.io --set cheImage=eclipse/che-server:nightly --set global.cheWorkspacesNamespace=che   /home/ivinokur/.cache/chectl/templates/kubernetes/helm/che/
Error: validation failed: error validating "": error validating data: [unknown object type "nil" in ConfigMap.data.CHE_LOGGER_CONFIG, unknown object type "nil" in ConfigMap.data.CHE_OAUTH_GITHUB_CLIENTID, unknown object type "nil" in ConfigMap.data.CHE_OAUTH_GITHUB_CLIENTSECRET, unknown object type "nil" in ConfigMap.data.CHE_WORKSPACE_HTTPS__PROXY, unknown object type "nil" in ConfigMap.data.CHE_WORKSPACE_HTTP__PROXY, unknown object type "nil" in ConfigMap.data.CHE_WORKSPACE_NO__PROXY]
Release "che" does not exist. Installing it now.
    at makeError (/snapshot/chectl/node_modules/execa/index.js:174:9)
    at module.exports.Promise.all.then.arr (/snapshot/chectl/node_modules/execa/index.js:278:16)`


minikube version: v1.1.0
chectl version: chectl/0.0.2-eb4948d linux-x64 node-v10.15.3

**Comment by benoitf** [comment]
could you list as well helm version ?

does `helm delete --purge che`  is helping ?

I just ran che on top of minikube on a fresh install
```
  ✔ ✈️  Minikube preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if minikube is installed
    ✔ Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    ✔ Verify if minikube ingress addon is enabled
    ↓ Enable minikube ingress addon [skipped]
      → Ingress addon is already enabled.
    ✔ Retrieving minikube IP and domain for ingress URLs...192.168.99.119.nip.io.
  ✔ 🏃‍  Running Helm to install Che
    ✔ Verify if helm is installed
    ✔ Create Tiller Role Binding...done.
    ✔ Create Tiller Service Account...done.
    ✔ Create Tiller RBAC
    ✔ Create Tiller Service...done.
    ✔ Preparing Che Helm Chart...done.
    ✔ Updating Helm Chart dependencies...done.
    ✔ Deploying Che Helm Chart...done.
  ✔ ✅  Post installation checklist
    ✔ Che pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Retrieving Che Server URL...http://che-che.192.168.99.119.nip.io
    ✔ Che status check
Command server:start has completed successfully.
```

**Comment by vinokurig** [comment]
helm version
```Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}

**Comment by vinokurig** [comment]
`helm delete --purge che` returned `Error: release: "che" not found`

**Comment by benoitf** [comment]
@vinokurig ok, could you try with helm 2.13.1 ?
It seems it's related to helm v2.14.0

**Comment by benoitf** [comment]
related to https://github.com/helm/helm/issues/5750

**Comment by benoitf** [comment]
@vinokurig I've opened https://github.com/che-incubator/chectl/pull/110 that is fixing the issue
