### ISSUE TITLE
Unable to restart Che

### ISSUE THREAD

**Issue by danidoedel** [che-incubator/chectl#176]
I'm not sure if that's a known issue already or if it's related to #77, but I will leave this here anyway. 
The first `chectl server:start` works as expected, but after shutting down everything and starting everything again I get this error. Any idea what's causing this? Deleting and redeploying works.

```
√ ✈️  Minikube preflight checklist
    √ Verify if kubectl is installed
    √ Verify if minikube is installed
    √ Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    √ Verify if minikube ingress addon is enabled
    ↓ Enable minikube ingress addon [skipped]
      → Ingress addon is already enabled.
    √ Retrieving minikube IP and domain for ingress URLs...192.168.99.102.nip.io.
  > 🏃‍  Running Helm to install Che
    √ Verify if helm is installed
    √ Create Tiller Role Binding...it already exist.
    √ Create Tiller Service Account...it already exist.
    × Create Tiller RBAC
      → ENOENT: no such file or directory, open 'templates\kubernetes\helm\che\tiller-rbac.yaml'
      Create Tiller Service
      Preparing Che Helm Chart
      Updating Helm Chart dependencies
      Deploying Che Helm Chart
Error: ENOENT: no such file or directory, open 'templates/kubernetes/helm/che/tiller-rbac.yaml'
    at Object.fs.openSync (pkg/prelude/bootstrap.js:488:32)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:684:36)
    at HelmHelper.<anonymous> (C:/snapshot/chectl/lib/installers/helm.js:0:0)
    at Generator.next (<anonymous>)
    at __awaiter (C:/snapshot/chectl/node_modules/tslib/tslib.js:110:75)
    at new Promise (<anonymous>)
```

**Comment by danidoedel** [comment]
Nevermind... running as administrator would have been a great idea :D
