### ISSUE TITLE
Command server:start fails if che helm chart has status DELETE or DELETING

### ISSUE THREAD

**Issue by l0rd** [che-incubator/chectl#18]
If Che Helm Chart is in `DELETING` status: 

```
$ helm list --all
NAME	REVISION	UPDATED                 	STATUS  	CHART    	APP VERSION	NAMESPACE
che 	1       	Tue Dec 11 19:57:47 2018	DELETING	che-0.1.0	           	kube-che
```

and the command server:start is executed the following error is shown:

```
  ✔ Verify if namespace kube-che exist
  ↓ Verify if Che server is already running [skipped]
    → Che namespace doesn't exist.
  ✖ Deploy Che Server
    → Error: UPGRADE FAILED: "che" has no deployed releases
    Waiting for Che Server to start and respond
    Retrieving Che Server URL
Error: Command failed: /bin/sh -c helm upgrade /
                            --install che /
                            --namespace kube-che /
                            --set global.ingressDomain=$(minikube ip).nip.io /
                            --set cheImage=eclipse/che-server:nightly /
                            --set global.cheWorkspacesNamespace=kube-che /
                            /Users/mloriedo/Library/Caches/chectl/templates/kubernetes/helm/che/
Error: UPGRADE FAILED: "che" has no deployed releases
    at makeError (~/github/chectl/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (~/github/chectl/node_modules/execa/index.js:278:16)
    at <anonymous>
```

**Comment by l0rd** [comment]
To reproduce it (supposing that Che chart has already been installed):

```
$ helm delete che
Error: deletion completed with 4 error(s): release "che": object "" not found, skipping delete; release "che": object "" not found, skipping delete; release "che": object "" not found, skipping delete; release "che": object "" not found, skipping delete
$ helm list -a
NAME	REVISION	UPDATED                 	STATUS 	CHART    	APP VERSION	NAMESPACE
che 	4       	Sat Mar  2 03:31:52 2019	DELETED	che-0.1.0	           	kube-che
$ ./bin/run server:start
  ✔ Platform preflight checklist (minikube) ✈️
    ✔ Verify if kubectl is installed
    ✔ Verify if minikube is installed
    ✔ Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    ✔ Verify if minikube ingress addon is enabled
    ↓ Enable minikube ingress addon [skipped]
      → Ingress addon is already enabled.
    ✔ Retrieving minikube IP and domain for ingress URLs...192.168.64.47.nip.io.
  ❯ Running the installer (Helm) 🏎️
    ✔ Verify if helm is installed
    ✔ Create Tiller Role Binding...it already exist.
    ✔ Create Tiller Service Account...it already exist.
    ✔ Create Tiller RBAC
    ✔ Create Tiller Service...it already exist.
    ✔ Preparing Che Helm Chart...done.
    ✔ Updating Helm Chart dependencies...done.
    ✖ Deploying Che Helm Chart
      → Error: UPGRADE FAILED: "che" has no deployed releases
Error: Command failed: /bin/sh -c helm upgrade /
                            --install che /
                            --namespace kube-che /
                            --set global.ingressDomain=192.168.64.47.nip.io /
                            --set cheImage=eclipse/che-server:nightly /
                            --set global.cheWorkspacesNamespace=kube-che /
                              /Users/mloriedo/Library/Caches/chectl/templates/kubernetes/helm/che/
Error: UPGRADE FAILED: "che" has no deployed releases
    at makeError (~/github/chectl/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (~/github/chectl/node_modules/execa/index.js:278:16)
```

**Comment by l0rd** [comment]
Related to https://github.com/helm/helm/issues/3208#issuecomment-348154521

**Comment by l0rd** [comment]
We should probably implement what is described in this issue comment https://github.com/helm/helm/issues/3353#issuecomment-385222233:

`helm upgrade --install`

**if** `FAIL` **then**
- **if** `revision=1` 
- **then** `helm delete --purge`
- **else** `helm rollback`
