### ISSUE TITLE
Unable to start server after delete on minikube using helm chart

### ISSUE THREAD

**Issue by metlos** [che-incubator/chectl#199]
When a server is deleted using `chectl server:delete` it is not possible to start it again.

```
$ chectl server:delete  
  ✔ Verify Kubernetes API...OK
  ✔ Delete all deployments...OK
  ✔ Delete all services...OK
  ✔ Delete all ingresses...OK
  ✔ Delete configmaps che and che-operator...OK
  ✔ Delete rolebindings che, che-operator, che-workspace-exec and che-workspace-view...OK
  ✔ Delete service accounts che, che-operator, che-workspace...OK
  ✔ Delete PVC postgres-data and che-data-volume...OK
  ✔ Delete pod che-operator...OK
  ✔ Purge che Helm chart...OK
 $ chectl server:start -m --installer=helm
  ✔ ✈️  Minikube preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if minikube is installed
    ✔ Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    ✔ Verify if minikube ingress addon is enabled
    ↓ Enable minikube ingress addon [skipped]
      → Ingress addon is already enabled.
    ✔ Retrieving minikube IP and domain for ingress URLs...192.168.99.112.nip.io.
  ❯ 🏃  Running Helm to install Che
    ✔ Verify if helm is installed
    ✔ Create Tiller Role Binding...done.
    ✔ Create Tiller Service Account...done.
    ✔ Create Tiller RBAC
    ✔ Create Tiller Service...done.
    ✔ Preparing Che Helm Chart...done.
    ✔ Updating Helm Chart dependencies...done.
    ✖ Deploying Che Helm Chart
      → Release "che" does not exist. Installing it now.
Error: Command failed: /bin/sh -c helm upgrade --install che --force --namespace che --set global.ingressDomain=192.168.99.112.nip.io --set cheImage=eclipse/che-server:nightly --set global.cheWorkspacesNamespace=che -f /home/lkrejci/.cache/chectl/templates/kubernetes/helm/che/values/multi-user.yaml  /home/lkrejci/.cache/chectl/templates/kubernetes/helm/che/
Error: release che failed: persistentvolumeclaims "postgres-data" already exists
Release "che" does not exist. Installing it now.
    at makeError (/snapshot/chectl/node_modules/execa/index.js:174:9)
    at module.exports.Promise.all.then.arr (/snapshot/chectl/node_modules/execa/index.js:278:16)
```

Note that `che-operator` seems to handle the situation ok.

**Comment by metlos** [comment]
Closing :) This probably was caused by trying to create it to early after the delete before k8s what it had actually done...
