### ISSUE TITLE
chectl fails with helm v3.0 on kubernetes

### ISSUE THREAD

**Issue by dcermak** [che-incubator/chectl#302]
I've tried to install che via chectl on a test kubernetes installation on top of openSUSE Tumbleweed Kubic:
```
# chectl server:start --platform=k8s --domain=44.71.0.62
  ✔ ✈️  Kubernetes preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify remote kubernetes status...done.
    ✔ Verify domain is set...set to 44.71.0.62.
  ❯ 🏃‍  Running Helm to install Che
    ✔ Verify if helm is installed
    ✔ Create Tiller Role Binding...it already exists.
    ✔ Create Tiller Service Account...it already exists.
    ✔ Create Tiller RBAC
    ✖ Create Tiller Service
      → error: E_COMMAND_FAILED
      Preparing Che Helm Chart
      Updating Helm Chart dependencies
      Deploying Che Helm Chart
Error: Command "helm init --service-account tiller --wait" failed with return code 1
stderr: Error: unknown flag: --service-account
stdout:
error: E_COMMAND_FAILED
    at HelmHelper.<anonymous> (/usr/local/lib/chectl/lib/installers/helm.js:193:23)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/chectl/node_modules/tslib/tslib.js:107:62)
```

I've installed chectl from the next channel and have the following versions installed:
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-21T12:00:00Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-21T12:00:00Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
# helm version
version.BuildInfo{Version:"v3.0+unreleased", GitCommit:"", GitTreeState:"", GoVersion:"go1.12.7"}

**Comment by benoitf** [comment]
@dcermak could you please open issues on https://github.com/eclipse/che/issues

Templates there: https://github.com/che-incubator/chectl/issues/new/choose is saying to not open issues on this issue tracker.

**Comment by benoitf** [comment]
and if you don't file issues, I will in the coming days.
