### ISSUE TITLE
Allow to configure timeout for download of images when using operator

### ISSUE THREAD

**Issue by apupier** [che-incubator/chectl#97]
```
> chectl server:start -a operator
  √ ✈️  Minikube preflight checklist
    √ Verify if kubectl is installed
    √ Verify if minikube is installed
    √ Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    √ Verify userland-proxy is disabled...done.
    √ Verify if minikube ingress addon is enabled
    √ Enable minikube ingress addon
    √ Retrieving minikube IP and domain for ingress URLs...192.168.1.25.nip.io.
  √ 🏃‍  Running the Che Operator
    √ Create Namespace (che)...done.
    √ Create ServiceAccount che-operator...done.
    √ Create RoleBinding che-operator in namespace che...done.
    √ Create ConfigMap che-operator in namespace che...done.
    √ Patch ConfigMap che-operator in namespace che...done.
    √ Delete Pod che-operator in namespace che if it exist...the Pod doesn't exist. Skipping.
    √ Waiting 5 seconds for the new ServiceAccount and RoleBindings to be flushed...done.
    √ Create che-operator Pod in namespace che...done.
  > ✅  Post installation checklist
    √ PostgreSQL pod bootstrap
      √ scheduling...done.
      √ downloading images...done.
      √ starting...done.
    > Keycloak pod bootstrap
      √ scheduling...done.
      × downloading images
        → ERR_TIMEOUT
        starting
      Che pod bootstrap
      Retrieving Che Server URL
      Che status check
Error: ERR_TIMEOUT
    at KubeHelper.<anonymous> (C:/snapshot/chectl/lib/api/kube.js:0:0)
    at Generator.next (<anonymous>)
    at fulfilled (C:/snapshot/chectl/node_modules/tslib/tslib.js:104:62)
```

it would be nice to allow to configure the timeout and/or to explain how to pull the correct image in another way

**Comment by l0rd** [comment]
@apupier good idea
