### ISSUE TITLE
ERR_TIMEOUT when scheduling Che pod bootstrap using minishift-addon

### ISSUE THREAD

**Issue by apupier** [che-incubator/chectl#98]
```
chectl server:start -a minishift-addon
  √ ✈️  Minikube preflight checklist
    √ Verify if kubectl is installed
    √ Verify if minikube is installed
    √ Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    √ Verify userland-proxy is disabled...done.
    √ Verify if minikube ingress addon is enabled
    ↓ Enable minikube ingress addon [skipped]
      → Ingress addon is already enabled.
    √ Retrieving minikube IP and domain for ingress URLs...192.168.1.27.nip.io.
  √ 🏃‍  Running the Che minishift-addon
    √ Apply Che addon...done.
  > ✅  Post installation checklist
    > Che pod bootstrap
      × scheduling
        → ERR_TIMEOUT
        downloading images
        starting
      Retrieving Che Server URL
      Che status check
Error: ERR_TIMEOUT
    at KubeHelper.<anonymous> (C:/snapshot/chectl/lib/api/kube.js:0:0)
    at Generator.next (<anonymous>)
    at fulfilled (C:/snapshot/chectl/node_modules/tslib/tslib.js:104:62)
```

**Comment by l0rd** [comment]
@apupier is this error consistent? I mean if you re-run `chectl sever:start` do you still have the same error? I am wondering if that a slow network problem while kube is downloading an image or if it is a `chectl` problem.

**Comment by apupier** [comment]
I retried 2 times in a row to call `chectl server:start -a minishift-addon` and I still have the same error

**Comment by benoitf** [comment]
I'm having as well these issues on slow networks

**Comment by apupier** [comment]
For information, I have a 23.5Mb/s network download speed.

**Comment by l0rd** [comment]
@apupier what version of minishift are you using?

**Comment by apupier** [comment]
> what version of minishift are you using?

in this case, I was on minikube.
`minikube version: v1.0.1`

I planned to try also with a minishift but as it is taking at least half an hour to create a minishift instance, not done yet.

If you are asking, I suspect that minishift-addon can be applied only on a minishift instance? Which means that we need to specify the platform to minishift and the installer to minishift-addon explicitely? If minishift-addon is not working on minikube,  wias expecting an error when chectl was reading the argument s to mention tha tthe combination is not supported.

**Comment by apupier** [comment]
with the fix for space in path https://github.com/che-incubator/chectl/pull/99 , I also have the same error when using `chectl server:start` (with default so with helm):

```
  √ ✈️  Minikube preflight checklist
    √ Verify if kubectl is installed
    √ Verify if minikube is installed
    √ Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    √ Verify userland-proxy is disabled...done.
    √ Verify if minikube ingress addon is enabled
    ↓ Enable minikube ingress addon [skipped]
      → Ingress addon is already enabled.
    √ Retrieving minikube IP and domain for ingress URLs...192.168.1.28.nip.io.
  √ 🏃‍  Running Helm to install Che
    √ Verify if helm is installed
    √ Create Tiller Role Binding...it already exist.
    √ Create Tiller Service Account...it already exist.
    √ Create Tiller RBAC
    √ Create Tiller Service...it already exist.
    √ Preparing Che Helm Chart...done.
    √ Updating Helm Chart dependencies...done.
    √ Deploying Che Helm Chart...done.
  > ✅  Post installation checklist
    > Che pod bootstrap
      × scheduling
        → ERR_TIMEOUT
        downloading images
        starting
      Retrieving Che Server URL
      Che status check
Error: ERR_TIMEOUT
    at KubeHelper.<anonymous> (C:/git/chectl/src/api/kube.ts:281:11)
    at Generator.next (<anonymous>)
    at fulfilled (C:/git/chectl/src/api/kube.ts:14:58)
```

in Kubernetes explorer, seems nothing is related to Che:
![image](https://user-images.githubusercontent.com/1105127/57679195-ff926900-762a-11e9-839d-3ab46343ba70.png)

**Comment by l0rd** [comment]
Yes so sorry. The minishift addon won't work on minikube. We should raise an error (I have just created a separate issue). I was asking for the version of minishift because the addon (that is shipped with minishift itself) had a bug in previous versions (other issue).

Regarding your last try: is the che pod started? You can check it with `kubectl get pod -n che`

**Comment by apupier** [comment]
> Regarding your last try: is the che pod started? You can check it with `kubectl get pod -n che`

no, seems there is no che resources at all

```
C:\Users\Aurelien Pupier>kubectl get pod -n che
No resources found.
```

**Comment by l0rd** [comment]
Ok and what about `helm list -a`?

**Comment by apupier** [comment]
```
C:\Users\Aurelien Pupier>helm list -a
Error: configmaps is forbidden: User "system:serviceaccount:kube-system:tiller" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
```

**Comment by l0rd** [comment]
It looks like the RBAC step didn't work properly. Can you try to apply it manually?

```bash
kubectl apply -f https://raw.githubusercontent.com/che-incubator/chectl/master/templates/kubernetes/helm/che/tiller-rbac.yaml
```

**Comment by l0rd** [comment]
ok we should have found the problem. I have created #102 that should fix the problem. Can you try to

```bash
kubectl apply -f https://raw.githubusercontent.com/che-incubator/chectl/c765fedaa219f1e7b5604952e53319463d70bf35/templates/kubernetes/helm/che/tiller-rbac.yaml
```

and run `chectl server:start` again?

**Comment by apupier** [comment]
```
C:\Users\Aurelien Pupier>kubectl apply -f https://raw.githubusercontent.com/che-incubator/chectl/c765fedaa219f1e7b5604952e53319463d70bf35/templates/kubernetes/helm/che/tiller-rbac.yaml
error: SchemaError(io.k8s.api.authorization.v1beta1.SelfSubjectRulesReview): invalid object doesn't have additional properties
```

:'(

**Comment by apupier** [comment]
seems there is a lot of places with v1beta1:

![image](https://user-images.githubusercontent.com/1105127/57685174-9f55f400-7637-11e9-8c4c-88308470de14.png)

**Comment by l0rd** [comment]
To be clear: `v1beta1` is not itself a problem. Some API, with the new releases of kube, are promoted from `v1beta1` to `v1`. That's the case of `ClusterRoleBinding`. And it looks like there is something else as well. You should not look at the typescript code but at the templates folder. 

What is your kubectl version? I am not able to reproduce your issue but I suspect you have a newer version:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:37:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by apupier** [comment]
```
C:\Users\Aurelien Pupier>kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by apupier** [comment]
so seem i have an older version used which is provided by Docker...

```
C:\Users\Aurelien Pupier>which kubectl
/cygdrive/c/Program Files/Docker/Docker/Resources/bin/kubectl
```

searching how to override that

**Comment by apupier** [comment]
works better with a newer client:

```
C:\Users\Aurelien Pupier>kubectl apply -f https://raw.githubusercontent.com/che-incubator/chectl/master/templates/kubernetes/helm/che/tiller-rbac.yaml
clusterrolebinding.rbac.authorization.k8s.io/tiller-role-binding created
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
serviceaccount/tiller configured
```

**Comment by apupier** [comment]
now I'm back to a tiemout...
```
C:\git\chectl\bin>run.cmd server:start
  √ ✈️  Minikube preflight checklist
    √ Verify if kubectl is installed
    √ Verify if minikube is installed
    √ Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    √ Verify userland-proxy is disabled...done.
    √ Verify if minikube ingress addon is enabled
    ↓ Enable minikube ingress addon [skipped]
      → Ingress addon is already enabled.
    √ Retrieving minikube IP and domain for ingress URLs...192.168.1.28.nip.io.
  √ 🏃‍  Running Helm to install Che
    √ Verify if helm is installed
    √ Create Tiller Role Binding...it already exist.
    √ Create Tiller Service Account...it already exist.
    √ Create Tiller RBAC
    √ Create Tiller Service...it already exist.
    √ Preparing Che Helm Chart...done.
    √ Updating Helm Chart dependencies...done.
    √ Deploying Che Helm Chart...done.
  > ✅  Post installation checklist
    > Che pod bootstrap
      × scheduling
        → ERR_TIMEOUT
        downloading images
        starting
      Retrieving Che Server URL
      Che status check
Error: ERR_TIMEOUT
    at KubeHelper.<anonymous> (C:/git/chectl/src/api/kube.ts:281:11)
    at Generator.next (<anonymous>)
    at fulfilled (C:/git/chectl/src/api/kube.ts:14:58)
```

but with other results for previously asked commands:

```
C:\Users\Aurelien Pupier>kubectl get pod -n che
No resources found.

C:\Users\Aurelien Pupier>helm list -a

C:\Users\Aurelien Pupier>
```

**Comment by benoitf** [comment]
I think it's only pure `downloading images` timeout

could you try
```
kubectl get events --sort-by='.metadata.creationTimestamp'  --all-namespaces
```
and see the time it took to grab images
```
che           74s         Normal    ScalingReplicaSet         deployment/che                                   Scaled up replica set che-7db57dc95 to 1
che           74s         Normal    SuccessfulCreate          replicaset/che-7db57dc95                         Created pod: che-7db57dc95-mt584
che           74s         Normal    Scheduled                 pod/che-7db57dc95-mt584                          Successfully assigned che/che-7db57dc95-mt584 to minikube
che           74s         Normal    CREATE                    ingress/che-ingress                              Ingress che/che-ingress
che           74s         Normal    Provisioning              persistentvolumeclaim/che-data-volume            External provisioner is provisioning volume for claim "che/che-data-volume"
che           73s         Normal    Pulling                   pod/che-7db57dc95-mt584                          Pulling image "busybox"
che           71s         Normal    Pulled                    pod/che-7db57dc95-mt584                          Successfully pulled image "busybox"
che           71s         Normal    Created                   pod/che-7db57dc95-mt584                          Created container fmp-volume-permission
che           71s         Normal    Started                   pod/che-7db57dc95-mt584                          Started container fmp-volume-permission
che           70s         Normal    Pulling                   pod/che-7db57dc95-mt584                          Pulling image "eclipse/che-server:nightly"
che           47s         Normal    UPDATE                    ingress/che-ingress                              Ingress che/che-ingress
che           9s          Normal    Pulled                    pod/che-7db57dc95-mt584                          Successfully pulled image "eclipse/che-server:nightly"
che           9s          Normal    Started                   pod/che-7db57dc95-mt584                          Started container che
che           9s          Normal    Created                   pod/che-7db57dc95-mt584                          Created container che
```


I just tried to bump every components to their latest versions and it worked
```bash
$ helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```



```
$ chectl server:start
  ✔ ✈️  Minikube preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if minikube is installed
    ✔ Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    ✔ Verify userland-proxy is disabled...done.
    ✔ Verify if minikube ingress addon is enabled
    ↓ Enable minikube ingress addon [skipped]
      → Ingress addon is already enabled.
    ✔ Retrieving minikube IP and domain for ingress URLs...192.168.99.116.nip.io.
  ✔ 🏃‍  Running Helm to install Che
    ✔ Verify if helm is installed
    ✔ Create Tiller Role Binding...done.
    ✔ Create Tiller Service Account...done.
    ✔ Create Tiller RBAC
    ✔ Create Tiller Service...done.
    ✔ Preparing Che Helm Chart...done.
    ✔ Updating Helm Chart dependencies...done.
    ✔ Deploying Che Helm Chart...done.
  ✔ ✅  Post installation checklist
    ✔ Che pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Retrieving Che Server URL...http://che-che.192.168.99.116.nip.io
    ✔ Che status check
```

**Comment by apupier** [comment]
```
C:\Users\Aurelien Pupier>kubectl get events --sort-by='.metadata.creationTimestamp'  --all-namespaces
error: couldn't find any field with path "{.'.metadata.creationTimestamp'}" in the list of objects
```

**Comment by benoitf** [comment]
ok probably the events are gone now.

**Comment by apupier** [comment]
I tried again to call the `chectl server:start` and called several times `kubectl get events --sort-by='.metadata.creationTimestamp'  --all-namespaces` while there was a spinning cursor on Che pod bootstrap -> scheduling but i still have the same message `error: couldn't find any field with path "{.'.metadata.creationTimestamp'}" in the list of objects`

**Comment by benoitf** [comment]
ok then could you try without the sort ?

```
$ kubectl get events --all-namespaces
```

**Comment by apupier** [comment]
```
C:\Users\Aurelien Pupier>kubectl get events --all-namespaces
No resources found.
```
seems nothing is happening to the kubernetes instance....

**Comment by benoitf** [comment]
there is now a configurable timeout
